"""Dump every standalone per-object .kcl collision file bundled in each track's course archive
(NOT the main course.kcl terrain mesh -- these are the small files individual placed objects load
by name, e.g. kinoko_r.kcl), with real stats (triangle count, which KCL type/variant combinations
actually appear), for every race track, in one pass.

Real format, ported directly from Kinoko's own decompiled parser (source/game/field/KColData.cc,
KCollisionTypes.hh) rather than guessed: header = 4x u32 (pos/normal/prism/block offsets), each
prism is 16 bytes (f32 height, then 5x u16: pos index, face-normal index, 3x edge-normal index,
attribute), attribute's low 5 bits are the KCL type (KCollisionTypes.hh's COL_TYPE_* enum, 0-0x1f),
bits 5-7 are the variant.

Also does a best-effort (heuristic, NOT ground truth) match of each track's placed objects against
the .kcl files in that same archive, by comparing the object's flow name/resource names against
kcl file names -- useful as a starting guess, but the REAL kcl name an object loads is decided by
its own C++ getKclName() override (e.g. ObjectKinokoUd always returns "kinoko_r" regardless of which
resource variant it's actually showing), so this can be wrong for any object with custom
getKclName() logic. Cross-check against source before trusting it for a specific object.

Usage:
    python tools/dump_all_kcl.py [path/to/MKWii]

Output: tools/data/all_kcl_files.json --
    {folder: {kcl_filename: {triangles, types: {"0 (ROAD) variant 0": count, ...}}}}
plus tools/data/all_object_placements.json (if already generated by dump_all_object_settings.py)
gets cross-referenced for the heuristic object->kcl guesses, printed to stdout (not saved, since
it's a guess -- re-run and re-read the printed list rather than trusting a stale file for this part).
"""

import json
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import brres_to_glb as b
import export_objects as eo

OUT_DIR = os.path.join(HERE, 'data')
OUT_FILE = os.path.join(OUT_DIR, 'all_kcl_files.json')
PLACEMENTS_FILE = os.path.join(OUT_DIR, 'all_object_placements.json')

TRACKS = [
    'beginner_course', 'farm_course', 'kinoko_course', 'factory_course', 'castle_course',
    'shopping_course', 'boardcross_course', 'truck_course', 'senior_course', 'ridgehighway_course',
    'treehouse_course', 'koopa_course', 'rainbow_course', 'volcano_course', 'desert_course',
    'water_course', 'old_peach_gc', 'old_mario_gc', 'old_waluigi_gc', 'old_donkey_gc',
    'old_falls_ds', 'old_desert_ds', 'old_garden_ds', 'old_town_ds', 'old_mario_sfc',
    'old_obake_sfc', 'old_mario_64', 'old_sherbet_64', 'old_koopa_64', 'old_donkey_64',
    'old_koopa_gba', 'old_heyho_gba',
]

# KCollisionTypes.hh's COL_TYPE_* enum (0-0x1f), for readable output.
COL_TYPE_NAMES = {
    0x00: 'ROAD', 0x01: 'SLIPPERY_ROAD', 0x02: 'WEAK_OFF_ROAD', 0x03: 'OFF_ROAD',
    0x04: 'HEAVY_OFF_ROAD', 0x05: 'SLIPPERY_ROAD_2', 0x06: 'BOOST_PAD', 0x07: 'BOOST_RAMP',
    0x08: 'JUMP_PAD', 0x09: 'ITEM_ROAD', 0x0a: 'SOLID_OOB', 0x0b: 'MOVING_WATER',
    0x0c: 'WALL', 0x0d: 'INVISIBLE_WALL', 0x0e: 'ITEM_WALL', 0x0f: 'WALL_2',
    0x10: 'FALL_BOUNDARY', 0x11: 'CANNON_TRIGGER', 0x12: 'FORCE_RECALCULATE_ROUTE',
    0x13: 'HALFPIPE_RAMP', 0x14: 'PLAYER_WALL', 0x15: 'MOVING_ROAD', 0x16: 'STICKY_ROAD',
    0x17: 'ROAD2', 0x18: 'SOUND_TRIGGER', 0x19: 'WEAK_WALL', 0x1a: 'EFFECT_TRIGGER',
    0x1b: 'ITEM_STATE_MODIFIER', 0x1c: 'HALFPIPE_INVISIBLE_WALL', 0x1d: 'ROTATING_ROAD',
    0x1e: 'SPECIAL_WALL', 0x1f: 'INVISIBLE_WALL2',
}


def parse_kcl(data):
    """{triangles, types: {"TYPE_NAME variant N": count}} for one .kcl file's prism list."""
    pos_off, nrm_off, prism_off, block_off = struct.unpack_from('>4I', data, 0)
    prism_size = 16
    count = (block_off - prism_off) // prism_size
    types = {}
    for i in range(1, count):  # prism 0 is a padding entry, real data is 1-indexed
        attribute = struct.unpack_from('>H', data, prism_off + i * prism_size + 14)[0]
        col_type = attribute & 0x1f
        variant = (attribute >> 5) & 0x7
        key = '%s variant %d' % (COL_TYPE_NAMES.get(col_type, 'UNKNOWN_0x%x' % col_type), variant)
        types[key] = types.get(key, 0) + 1
    return {'triangles': count - 1, 'types': types}


def main():
    mkwii = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', '..', 'MKWii')
    course_dir = os.path.join(mkwii, 'Race', 'Course')

    placements = {}
    if os.path.exists(PLACEMENTS_FILE):
        placements = json.load(open(PLACEMENTS_FILE))

    os.makedirs(OUT_DIR, exist_ok=True)
    out = {}

    for folder in TRACKS:
        path = os.path.join(course_dir, folder + '.szs')
        if not os.path.exists(path):
            print('  ! missing %s' % path)
            continue
        data = b.yaz0_decompress(open(path, 'rb').read())
        files = b.u8_files(data)
        kcl_names = sorted(f for f in files if f.lower().endswith('.kcl'))
        track_out = {}
        for name in kcl_names:
            try:
                track_out[name] = parse_kcl(files[name])
            except Exception as e:
                print('  ! %s/%s: %r' % (folder, name, e))
        out[folder] = track_out
        print('%-22s %2d .kcl files (%s)' % (folder, len(kcl_names), ', '.join(kcl_names)))

        # Heuristic object -> kcl guess: does any placed object's flow name or resource name match
        # a .kcl file present here? Printed only -- see the module docstring on why this is a guess.
        kcl_stems = {os.path.splitext(n)[0] for n in kcl_names}
        for p in placements.get(folder, []):
            candidates = {p['name']} | set(p.get('resources', []))
            hits = candidates & kcl_stems
            if hits:
                print('    %-20s (id %d) likely uses: %s' % (p['name'], p['id'], ', '.join(sorted(hits))))

    with open(OUT_FILE, 'w') as f:
        json.dump(out, f, indent=1)
    print('\nwrote %s' % OUT_FILE)


if __name__ == '__main__':
    main()
